name: decaylanguage_demo
dependencies:
  - python>=3.7
  - pandas>=0.24
  - attrs>=19.2
  - pip>=9
  - jupyterlab>=0.35
  - six>=1.11
  - numpy>=1.12
  - pydot>=1.3.0
  - pip:
    - hepunits>=1.2.0
    - particle==0.10.*
    - lark-parser>=0.8.0
    - plumbum>=1.6.9
    - RISE
    - graphviz
