name: decaylanguage_demo
dependencies:
  - python>=3.7
  - pandas>=0.24
  - attrs>=17.4
  - pip>=9
  - jupyterlab>=0.35
  - six>=1.11
  - numpy>=1.12
  - pydot>=1.3.0
  - pip:
    - hepunits>=1.0.0
    - particle==0.6.*
    - lark-parser>=0.6.3
    - plumbum>=1.6.6
    - RISE
    - graphviz
